be_search:
  version: '1.3'
  author: Markus Staab
  supportpage: forum.redaxo.de
  
  requires:
    addons:
      structure:
        min-version: '1.3'
      mediapool:
        min-version: '1.3'