language: php

php:
    - 5.5
    - 5.6
    - 7.0

sudo: false

notifications:
    email: false

cache:
    directories:
        - $HOME/.php-cs-fixer
        - $HOME/.composer/cache

install:
    - mysql -e 'create database redaxo_5_0;'
    - php redaxo/src/addons/tests/bin/setup.php
    - mkdir -p "$HOME/.php-cs-fixer"
    - "echo '{\"require\": {\"fabpot/php-cs-fixer\": \"~2.0@dev\"}}' > \"$HOME/.php-cs-fixer/composer.json\""
    - travis_retry composer update --no-interaction --working-dir "$HOME/.php-cs-fixer"

script:
    - php redaxo/src/addons/tests/bin/run_tests.php
    - php "$HOME/.php-cs-fixer/vendor/bin/php-cs-fixer" fix --cache-file "$HOME/.php-cs-fixer/.php_cs.$TRAVIS_PHP_VERSION.cache" --dry-run --diff --verbose
