language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0

matrix:
    allow_failures:
        - php: 7.0

before_script:
    - mysql -e 'create database redaxo_5_0;'
    - php redaxo/src/addons/tests/bin/setup.php
script:
    - php redaxo/src/addons/tests/bin/run_tests.php
    - php coding_standards.phar check --hide-process
