package: media_manager
version: '5.0 a1'
author: 'Markus Staab, Jan Kristinus'
supportpage: www.redaxo.org/de/forum/

page:
  title: 'Media Manager'
  perm: media_manager[]
  subpages:
    overview: { title: 'translate:media_manager_subpage_desc' }
    types: { title: 'translate:media_manager_subpage_types' }
    settings: { title: 'translate:media_manager_subpage_config' }
    clear_cache: { title: 'translate:media_manager_subpage_clear_cache', href: { page: media_manager, func: clear_cache } }

requires:
  php:
    extensions: [gd]
