package: structure
version: '5.0-alpha7'
author: Markus Staab
supportpage: www.redaxo.org/de/forum/

page:
    title: translate:structure
    perm: structure/hasStructurePerm
    block: system
    prio: 10
    pjax: true

pages:
    linkmap:
        title: translate:linkmap
        main: true
        block: system
        popup: true
        hidden: true
        perm: structure/hasStructurePerm
        pjax: true

system_plugins: [content]
