name: 'translate:structure'
version: '1.3'
author: Markus Staab
supportpage: www.redaxo.org/de/forum/
perm: structure/hasStructurePerm
navigation:
  block: system
  prio: 10

requires:
  addons:
    templates:
      min-version: '1.3'