package: structure
version: '5.0 a1'
author: Markus Staab
supportpage: www.redaxo.org/de/forum/

navigation:
  title: 'translate:structure'
  perm: structure/hasStructurePerm
  block: system
  prio: 10

system_plugins: [content, linkmap]
