name: 'translate:structure'
version: '5.0 a1'
author: Markus Staab
supportpage: www.redaxo.org/de/forum/
perm: structure/hasStructurePerm
navigation:
  block: system
  prio: 10

requires:
  addons:
    templates:
      min-version: '5.0 a1'