version: '1.0'
author: Gregor Harlan
supportpage: www.redaxo.org/de/forum

name: 'translate:install_name'
perm: admin[]
navigation:
  block: system

requires:
  redaxo:
    min-version: '5.0'