version: '5.0 alpha6'
author: Gregor Harlan
supportpage: www.redaxo.org/de/forum

name: 'translate:name'
perm: admin[]
navigation:
  block: system
  prio: 80
pages:
  - [settings, 'translate:settings']
  
system_plugins: [core, packages]
  
requires:
  redaxo:
    min-version: '5.0.alpha3'
  php:
    extensions: [phar, zlib]
