version: '5.0 alpha5'
author: Gregor Harlan
supportpage: www.redaxo.org/de/forum

name: 'translate:install_name'
perm: admin[]
navigation:
  block: system
  
requires:
  redaxo:
    min-version: '5.0.alpha2'
  php:
    extensions: [phar, zlib]