image_resize:
  version: '1.3'
  author: 'Markus Staab, Jan Kristinus, Wolfgang Hutteger'
  name: 'Image Resize'
  perm: image_resize[]
  supportpage: forum.redaxo.de
  
  requires:
    php-extension:
      - gd