version: '5.0 a1'
author: 'Markus Staab'
supportpage: www.redaxo.org/de/forum/

navigation:
  title: 'translate:modules'
  perm: isAdmin
  block: system
  prio: 40
  subpages:
    '': {title: 'translate:modules'}
    actions: {title: 'translate:actions'}
