version: '5.0 alpha2'
author: 'Markus Staab, Brent R. Matzelle'
name: PHPMailer
perm: phpmailer[]
supportpage: www.redaxo.org/de/forum/

pages:
  - ['', 'translate:phpmailer_configuration']
  - ['example', 'translate:phpmailer_example']

requires:
  redaxo:
    min-version: '5.0.alpha3'