package: phpmailer
version: '5.0-alpha7'
author: 'Markus Staab, Brent R. Matzelle'
supportpage: www.redaxo.org/de/forum/

page:
    title: PHPMailer
    perm: phpmailer[]
    subpages:
        config: { title: 'translate:configuration' }
        example: { title: 'translate:example' }
