version: '5.0 a1'
author: Jan Kristinus, Gregor Harlan
supportpage: www.redaxo.org/de/forum/

navigation:
  title: 'translate:users'
  perm: users[]
  block: system
  prio: 50
  subpages:
    '': {title: 'translate:users', perm: admin}
    roles: {title: 'translate:roles', perm: admin}
