package: users
version: '5.0 a1'
author: Jan Kristinus, Gregor Harlan
supportpage: www.redaxo.org/de/forum/

load: early

navigation:
  title: 'translate:users'
  perm: users[]
  block: system
  prio: 50
  subpages:
    users: { title: 'translate:users', perm: admin }
    roles: { title: 'translate:roles', perm: admin }
