version: '5.0 alpha2'
author: 'Gregor Harlan'
supportpage: www.redaxo.org/de/forum/

name: 'translate:title'
perm: admin[]
pages:
  - ['', 'translate:title']
  - ['log', 'translate:log']

requires:
  redaxo:
    min-version: '5.0.alpha3'