package: cronjob
version: '5.0-alpha7'
author: 'Gregor Harlan'
supportpage: www.redaxo.org/de/forum/

page:
    title: 'translate:title'
    perm: admin[]
    pjax: true
    icon: rex-icon rex-icon-cronjob
    subpages:
        cronjobs: { title: 'translate:title' }
        log: { title: 'translate:log' }
