version:
  version: '0.2'
  author: Jan Kristinus
  supportpage: forum.redaxo.de
  
  requires:
    addons:
      structure:
        min-version: '1.3'
        plugins:
          content:
            min-version: '1.3'