version: '5.0 a1'
author: Markus Staab
supportpage: www.redaxo.org/de/forum/

navigation:
  title: 'Templates'
  perm: admin[]
  block: system
  prio: 30

requires:
  addons:
    modules:
      min-version: '5.0 a1'
