metainfo:
  version: '1.3'
  name: Meta Infos
  perm: admin[]
  author: 'Markus Staab, Jan Kristinus'
  supportpage: forum.redaxo.de
  
  dependencies:
    structure:
      min-version: '1.3'
    mediapool:
      min-version: '1.3'