version: '5.0 a1'
author: 'Jan Kristinus'
supportpage: www.redaxo.org/de/forum/

blocked_extensions: ['.php','.php3','.php4','.php5','.php6','.phtml','.pl','.asp','.aspx','.cfm','.jsp','.jsf','.bat','.sh','.cgi']
