version: '5.0 a1'
author: 'Markus Staab, Jan Kristinus'
supportpage: www.redaxo.org/de/forum/

navigation:
  title: Meta Infos
  perm: admin[]
  subpages:
    '': {title: 'translate:article'}
    categories: {title: 'translate:categories'}
    media: {title: 'translate:media'}

requires:
  addons:
    structure:
      min-version: '5.0 a1'
    mediapool:
      min-version: '5.0 a1'
